-- ==========================================
-- ESTRUCTURA DE BASE DE DATOS - SUPABASE
-- FERRETERÍA EL SERRUCHO
-- ==========================================

-- 1. Habilitar extensión trigram para soporte ortográfico (coincidencias aproximadas)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Tabla de productos (catálogo e inventario consolidados)
CREATE TABLE IF NOT EXISTS public.productos (
    codigo_interno text PRIMARY KEY,
    descripcion text,
    unidad text,
    codigo_barras text,
    costo numeric,
    precio_venta numeric,
    existencia numeric,
    actualizado_en timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    referencia text
);

-- 3. Tabla de tasas de cambio dinámicas (Bolívares por Dólar).
--    NOMBRE CANÓNICO EN PRODUCCIÓN: "tazas" (todo el bot consulta /rest/v1/tazas).
CREATE TABLE IF NOT EXISTS public.tazas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text,
    bcv_usd numeric,
    bcv_eur numeric,
    binance_p2p numeric,
    tasa_promedio numeric,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabla de clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    codigo_cliente text PRIMARY KEY,
    nombre text,
    rif text,
    telefono text,
    direccion text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabla de sesiones de chat (control de estado bot/humano y rate limiting)
CREATE TABLE IF NOT EXISTS public.chat_sessions (
    telefono text PRIMARY KEY,
    estado text DEFAULT 'automatico' NOT NULL,
    msg_count integer DEFAULT 0 NOT NULL,
    window_start timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Tablas de transacciones de ventas
CREATE TABLE IF NOT EXISTS public.ventas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento text,
    fecha_emision date,
    rif_cliente text,
    total_neto numeric,
    total_impuesto numeric,
    status integer, -- 1 = aprobado / emitido
    numero_control text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    total_bruto numeric,
    metodo_pago text,
    id_unico bigint
);

CREATE TABLE IF NOT EXISTS public.ventas_detalle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento text,
    codigo_producto text,
    cantidad numeric,
    precio_venta numeric,
    costo_str text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    venta_id bigint REFERENCES public.ventas(id)
);

-- 7. Tablas de ordenes de cambio (Ingresos/Ajustes de inventario)
CREATE TABLE IF NOT EXISTS public.ordenes_cambio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_por uuid,
    nota text,
    status text, -- 'emitido' = aplicado
    pdf_url text,
    creado_en timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ordenes_cambio_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id bigint REFERENCES public.ordenes_cambio(id),
    codigo_producto text,
    descripcion text,
    existencia_actual numeric,
    nueva_existencia numeric,
    nota text,
    delta numeric
);

-- 8. Creación de índices para optimizar búsquedas
CREATE INDEX IF NOT EXISTS idx_productos_descripcion ON public.productos USING btree (descripcion);
CREATE INDEX IF NOT EXISTS idx_productos_barcode ON public.productos USING btree (codigo_barras);
CREATE INDEX IF NOT EXISTS idx_productos_referencia ON public.productos USING btree (referencia);

-- Índice GIN trigram para búsqueda difusa en descripción
CREATE INDEX IF NOT EXISTS idx_productos_desc_trgm ON public.productos USING gin (descripcion gin_trgm_ops);

-- Índice para búsqueda rápida de sesiones
CREATE INDEX IF NOT EXISTS idx_chat_sessions_updated ON public.chat_sessions USING btree (updated_at);

-- 9. Función para búsqueda difusa de productos
CREATE OR REPLACE FUNCTION public.buscar_productos(
    p_busqueda text,
    p_limite integer DEFAULT 5
)
RETURNS TABLE (
    codigo_interno text,
    descripcion text,
    precio_venta numeric,
    existencia numeric,
    score float
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.codigo_interno,
        p.descripcion,
        p.precio_venta,
        p.existencia,
        similarity(p.descripcion, p_busqueda)::float AS score
    FROM public.productos p
    WHERE p.descripcion % p_busqueda OR p.descripcion ILIKE ('%' || p_busqueda || '%')
    ORDER BY score DESC, p.existencia DESC
    LIMIT p_limite;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 10. Función para auditoría de movimientos de stock
CREATE OR REPLACE FUNCTION public.get_resumen_movimientos(p_codigo VARCHAR, p_limit INT DEFAULT 5)
RETURNS TABLE (
  fecha TEXT,
  tipo TEXT,
  cantidad NUMERIC,
  referencia TEXT
) AS $$
BEGIN
  RETURN QUERY
  (
    -- Ventas (Status = 1)
    SELECT 
      to_char(v.created_at, 'DD/MM/YYYY') as fecha,
      'venta'::TEXT as tipo,
      -(vd.cantidad)::NUMERIC as cantidad,
      ('Factura ' || COALESCE(vd.documento, ''))::TEXT as referencia
    FROM ventas_detalle vd
    JOIN ventas v ON vd.venta_id = v.id
    WHERE vd.codigo_producto = p_codigo AND v.status = 1
    
    UNION ALL
    
    -- Ajustes e Ingresos (Emitidos)
    SELECT 
      to_char(oc.creado_en, 'DD/MM/YYYY') as fecha,
      CASE WHEN oci.delta > 0 THEN 'ingreso' ELSE 'ajuste' END::TEXT as tipo,
      oci.delta::NUMERIC as cantidad,
      COALESCE(oc.nota, 'Ajuste')::TEXT as referencia
    FROM ordenes_cambio_items oci
    JOIN ordenes_cambio oc ON oci.orden_id = oc.id
    WHERE oci.codigo_producto = p_codigo AND oc.status = 'emitido'
  )
  ORDER BY fecha DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

-- 12. Cola de atención: clientes que pidieron hablar con un empleado (escalación del bot).
--     El bot, al emitir [ESCALAR_HUMANO], inserta aquí (rol anon). La app de empleados se
--     suscribe por Realtime (rol authenticated) y muestra/atiende la cola.
CREATE TABLE IF NOT EXISTS public.atenciones_pendientes (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono     text NOT NULL,
    nombre       text,
    motivo       text,                                  -- último mensaje del cliente que disparó la escalación
    status       text NOT NULL DEFAULT 'pendiente',     -- 'pendiente' | 'atendido'
    creado_en    timestamp with time zone NOT NULL DEFAULT now(),
    atendido_en  timestamp with time zone,
    atendido_por uuid
);
COMMENT ON TABLE public.atenciones_pendientes IS
  'Cola de clientes en espera de atención de un empleado (escalación del bot). La app de empleados se suscribe por Realtime.';

-- Clave foránea a profiles (tabla del employee-app). Se aplica solo si ya existe.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'profiles'
  ) THEN
    BEGIN
      ALTER TABLE public.atenciones_pendientes
        ADD CONSTRAINT fk_atenciones_atendido_por
        FOREIGN KEY (atendido_por) REFERENCES public.profiles(id) ON DELETE SET NULL;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
  END IF;
END $$;

-- A lo sumo UNA atención pendiente por teléfono (evita duplicados si el cliente reescala).
CREATE UNIQUE INDEX IF NOT EXISTS uniq_atenciones_tel_pendiente
  ON public.atenciones_pendientes (telefono) WHERE status = 'pendiente';
CREATE INDEX IF NOT EXISTS idx_atenciones_status_creado
  ON public.atenciones_pendientes (status, creado_en);

ALTER TABLE public.atenciones_pendientes ENABLE ROW LEVEL SECURITY;

-- anon (n8n / backend): leer (dedup) + insertar (encolar)
DROP POLICY IF EXISTS "n8n - select atenciones" ON public.atenciones_pendientes;
CREATE POLICY "n8n - select atenciones" ON public.atenciones_pendientes
  FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "n8n - insert atenciones" ON public.atenciones_pendientes;
CREATE POLICY "n8n - insert atenciones" ON public.atenciones_pendientes
  FOR INSERT TO anon WITH CHECK (true);

-- Políticas para empleados: solo si is_active_employee() y validate_session() existen.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
             WHERE n.nspname = 'public' AND p.proname = 'is_active_employee')
  AND EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.proname = 'validate_session')
  THEN
    DROP POLICY IF EXISTS "Empleados - leer atenciones" ON public.atenciones_pendientes;
    CREATE POLICY "Empleados - leer atenciones" ON public.atenciones_pendientes
      FOR SELECT TO authenticated USING (is_active_employee());
    DROP POLICY IF EXISTS "Empleados - actualizar atenciones" ON public.atenciones_pendientes;
    CREATE POLICY "Empleados - actualizar atenciones" ON public.atenciones_pendientes
      FOR UPDATE TO authenticated USING (is_active_employee() AND validate_session())
      WITH CHECK (is_active_employee() AND validate_session());
  ELSE
    RAISE NOTICE 'Saltando políticas de empleados para atenciones_pendientes: is_active_employee() o validate_session() no existen todavía.';
  END IF;
END $$;

-- Realtime: la app recibe el aviso al instante.
ALTER TABLE public.atenciones_pendientes REPLICA IDENTITY FULL;
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.atenciones_pendientes;
  EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN others THEN RAISE NOTICE 'no se pudo agregar a supabase_realtime: %', SQLERRM;
  END;
END $$;

-- 13. Solicitudes de ayuda: el bot no encontró algo o el cliente refutó el resultado.
--     El bot inserta (anon) al emitir [PEDIR_AYUDA]; la app de empleados elige los productos
--     (solicitudes_ayuda_items) y marca 'resuelto'; el webhook n8n /reenviar-ayuda arma y reenvía
--     el mensaje al cliente y marca 'enviado'.
CREATE TABLE IF NOT EXISTS public.solicitudes_ayuda (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono     text NOT NULL,
    nombre       text,
    consulta     text,                                  -- lo que pidió el cliente (su mensaje / lista)
    motivo       text NOT NULL DEFAULT 'no_encontrado', -- 'no_encontrado' | 'refutado'
    status       text NOT NULL DEFAULT 'pendiente',     -- 'pendiente' | 'resuelto' | 'enviado' | 'descartado'
    creado_en    timestamp with time zone NOT NULL DEFAULT now(),
    resuelto_en  timestamp with time zone,
    resuelto_por uuid,
    enviado_en   timestamp with time zone
);
COMMENT ON TABLE public.solicitudes_ayuda IS
  'Solicitudes de ayuda del bot (no encontró / cliente refutó). La app elige productos y n8n reenvía al cliente.';

-- Clave foránea a profiles (tabla del employee-app). Se aplica solo si ya existe.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'profiles'
  ) THEN
    BEGIN
      ALTER TABLE public.solicitudes_ayuda
        ADD CONSTRAINT fk_solicitudes_resuelto_por
        FOREIGN KEY (resuelto_por) REFERENCES public.profiles(id) ON DELETE SET NULL;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
  END IF;
END $$;

-- Bandera "no hay stock": la app la marca (botón "no disponible") al resolver SIN productos;
-- el workflow "Reenviar Ayuda" la lee y le avisa al cliente que no hay disponibilidad.
ALTER TABLE public.solicitudes_ayuda ADD COLUMN IF NOT EXISTS no_disponible boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.solicitudes_ayuda_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id    bigint NOT NULL REFERENCES public.solicitudes_ayuda(id) ON DELETE CASCADE,
    codigo_producto text NOT NULL,
    descripcion     text,
    cantidad        numeric NOT NULL DEFAULT 1,
    precio_unitario numeric
);
CREATE INDEX IF NOT EXISTS idx_solicitudes_ayuda_items_sol ON public.solicitudes_ayuda_items (solicitud_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_solicitudes_tel_pendiente
  ON public.solicitudes_ayuda (telefono) WHERE status = 'pendiente';
CREATE INDEX IF NOT EXISTS idx_solicitudes_status_creado ON public.solicitudes_ayuda (status, creado_en);

ALTER TABLE public.solicitudes_ayuda       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitudes_ayuda_items ENABLE ROW LEVEL SECURITY;

-- anon (n8n): insertar (al escalar), leer (componer), actualizar status (marcar enviado)
DROP POLICY IF EXISTS "n8n - select solicitudes" ON public.solicitudes_ayuda;
CREATE POLICY "n8n - select solicitudes" ON public.solicitudes_ayuda FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "n8n - insert solicitudes" ON public.solicitudes_ayuda;
CREATE POLICY "n8n - insert solicitudes" ON public.solicitudes_ayuda FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "n8n - update solicitudes" ON public.solicitudes_ayuda;
CREATE POLICY "n8n - update solicitudes" ON public.solicitudes_ayuda FOR UPDATE TO anon USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "n8n - select solicitudes_items" ON public.solicitudes_ayuda_items;
CREATE POLICY "n8n - select solicitudes_items" ON public.solicitudes_ayuda_items FOR SELECT TO anon USING (true);

-- Políticas para empleados: solo si is_active_employee() y validate_session() existen.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
             WHERE n.nspname = 'public' AND p.proname = 'is_active_employee')
  AND EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.proname = 'validate_session')
  THEN
    DROP POLICY IF EXISTS "Empleados - leer solicitudes" ON public.solicitudes_ayuda;
    CREATE POLICY "Empleados - leer solicitudes" ON public.solicitudes_ayuda
      FOR SELECT TO authenticated USING (is_active_employee());
    DROP POLICY IF EXISTS "Empleados - resolver solicitudes" ON public.solicitudes_ayuda;
    CREATE POLICY "Empleados - resolver solicitudes" ON public.solicitudes_ayuda
      FOR UPDATE TO authenticated USING (is_active_employee() AND validate_session())
      WITH CHECK (is_active_employee() AND validate_session());
    DROP POLICY IF EXISTS "Empleados - leer items" ON public.solicitudes_ayuda_items;
    CREATE POLICY "Empleados - leer items" ON public.solicitudes_ayuda_items
      FOR SELECT TO authenticated USING (is_active_employee());
    DROP POLICY IF EXISTS "Empleados - escribir items" ON public.solicitudes_ayuda_items;
    CREATE POLICY "Empleados - escribir items" ON public.solicitudes_ayuda_items
      FOR ALL TO authenticated USING (is_active_employee() AND validate_session())
      WITH CHECK (is_active_employee() AND validate_session());
  ELSE
    RAISE NOTICE 'Saltando políticas de empleados para solicitudes_ayuda: is_active_employee() o validate_session() no existen todavía.';
  END IF;
END $$;

-- Realtime para la cola
ALTER TABLE public.solicitudes_ayuda REPLICA IDENTITY FULL;
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.solicitudes_ayuda;
  EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN others THEN RAISE NOTICE 'realtime: %', SQLERRM;
  END;
END $$;

-- 14. Suscripciones Web Push (notificaciones con la app CERRADA).
--     El emisor es la Edge Function 'send-push' + un trigger 'notify_push' (pg_net) sobre
--     solicitudes_ayuda y atenciones_pendientes, ambos desplegados en Supabase. La clave VAPID
--     privada y el secreto del trigger viven dentro de la función (NO en este repo público).
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id  uuid,
    endpoint     text NOT NULL UNIQUE,
    subscription jsonb NOT NULL,            -- objeto PushSubscription completo (endpoint + keys)
    user_agent   text,
    creado_en    timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Clave foránea a profiles (tabla del employee-app). Se aplica solo si ya existe.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'profiles'
  ) THEN
    BEGIN
      ALTER TABLE public.push_subscriptions
        ADD CONSTRAINT fk_push_empleado_id
        FOREIGN KEY (empleado_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
  END IF;
END $$;

-- Política para empleados: solo si is_active_employee() existe.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
             WHERE n.nspname = 'public' AND p.proname = 'is_active_employee')
  THEN
    DROP POLICY IF EXISTS "Empleados - gestionar push" ON public.push_subscriptions;
    CREATE POLICY "Empleados - gestionar push" ON public.push_subscriptions
      FOR ALL TO authenticated USING (is_active_employee()) WITH CHECK (is_active_employee());
  ELSE
    RAISE NOTICE 'Saltando política de empleados para push_subscriptions: is_active_employee() no existe todavía.';
  END IF;
END $$;
