-- ==========================================
-- ESTRUCTURA DE BASE DE DATOS - SUPABASE
-- FERRETERÍA EL SERRUCHO
-- ==========================================

-- 1. Habilitar extensión trigram para soporte ortográfico (coincidencias aproximadas)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Tabla de productos (catálogo e inventario consolidados)
CREATE TABLE IF NOT EXISTS public.productos (
    codigo_interno text PRIMARY KEY,
    descripcion text,
    unidad text,
    codigo_barras text,
    costo numeric,
    precio_venta numeric,
    existencia numeric,
    actualizado_en timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    referencia text
);

-- 3. Tabla de tasas de cambio dinámicas (Bolívares o pesos locales por Dólar)
--    NOTA: tabla renombrada de "tazas" a "tasas" (corrección ortográfica)
CREATE TABLE IF NOT EXISTS public.tasas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text,
    bcv_usd numeric,
    bcv_eur numeric,
    binance_p2p numeric,
    tasa_promedio numeric,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabla de clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    codigo_cliente text PRIMARY KEY,
    nombre text,
    rif text,
    telefono text,
    direccion text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabla de sesiones de chat (control de estado bot/humano y rate limiting)
CREATE TABLE IF NOT EXISTS public.chat_sessions (
    telefono text PRIMARY KEY,
    estado text DEFAULT 'automatico' NOT NULL,
    msg_count integer DEFAULT 0 NOT NULL,
    window_start timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Tablas de transacciones de ventas
CREATE TABLE IF NOT EXISTS public.ventas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento text,
    fecha_emision date,
    rif_cliente text,
    total_neto numeric,
    total_impuesto numeric,
    status integer, -- 1 = aprobado / emitido
    numero_control text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    total_bruto numeric,
    metodo_pago text,
    id_unico bigint
);

CREATE TABLE IF NOT EXISTS public.ventas_detalle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento text,
    codigo_producto text,
    cantidad numeric,
    precio_venta numeric,
    costo_str text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    venta_id bigint REFERENCES public.ventas(id)
);

-- 7. Tablas de ordenes de cambio (Ingresos/Ajustes de inventario)
CREATE TABLE IF NOT EXISTS public.ordenes_cambio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_por uuid,
    nota text,
    status text, -- 'emitido' = aplicado
    pdf_url text,
    creado_en timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ordenes_cambio_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id bigint REFERENCES public.ordenes_cambio(id),
    codigo_producto text,
    descripcion text,
    existencia_actual numeric,
    nueva_existencia numeric,
    nota text,
    delta numeric
);

-- 8. Creación de índices para optimizar búsquedas
CREATE INDEX IF NOT EXISTS idx_productos_descripcion ON public.productos USING btree (descripcion);
CREATE INDEX IF NOT EXISTS idx_productos_barcode ON public.productos USING btree (codigo_barras);
CREATE INDEX IF NOT EXISTS idx_productos_referencia ON public.productos USING btree (referencia);

-- Índice GIN trigram para búsqueda difusa en descripción
CREATE INDEX IF NOT EXISTS idx_productos_desc_trgm ON public.productos USING gin (descripcion gin_trgm_ops);

-- Índice para búsqueda rápida de sesiones
CREATE INDEX IF NOT EXISTS idx_chat_sessions_updated ON public.chat_sessions USING btree (updated_at);

-- 9. Función para búsqueda difusa de productos
CREATE OR REPLACE FUNCTION public.buscar_productos(
    p_busqueda text,
    p_limite integer DEFAULT 5
)
RETURNS TABLE (
    codigo_interno text,
    descripcion text,
    precio_venta numeric,
    existencia numeric,
    score float
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.codigo_interno,
        p.descripcion,
        p.precio_venta,
        p.existencia,
        similarity(p.descripcion, p_busqueda)::float AS score
    FROM public.productos p
    WHERE p.descripcion % p_busqueda OR p.descripcion ILIKE ('%' || p_busqueda || '%')
    ORDER BY score DESC, p.existencia DESC
    LIMIT p_limite;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 10. Función para auditoría de movimientos de stock
CREATE OR REPLACE FUNCTION public.get_resumen_movimientos(p_codigo VARCHAR, p_limit INT DEFAULT 5)
RETURNS TABLE (
  fecha TEXT,
  tipo TEXT,
  cantidad NUMERIC,
  referencia TEXT
) AS $$
BEGIN
  RETURN QUERY
  (
    -- Ventas (Status = 1)
    SELECT 
      to_char(v.created_at, 'DD/MM/YYYY') as fecha,
      'venta'::TEXT as tipo,
      -(vd.cantidad)::NUMERIC as cantidad,
      ('Factura ' || COALESCE(vd.documento, ''))::TEXT as referencia
    FROM ventas_detalle vd
    JOIN ventas v ON vd.venta_id = v.id
    WHERE vd.codigo_producto = p_codigo AND v.status = 1
    
    UNION ALL
    
    -- Ajustes e Ingresos (Emitidos)
    SELECT 
      to_char(oc.creado_en, 'DD/MM/YYYY') as fecha,
      CASE WHEN oci.delta > 0 THEN 'ingreso' ELSE 'ajuste' END::TEXT as tipo,
      oci.delta::NUMERIC as cantidad,
      COALESCE(oc.nota, 'Ajuste')::TEXT as referencia
    FROM ordenes_cambio_items oci
    JOIN ordenes_cambio oc ON oci.orden_id = oc.id
    WHERE oci.codigo_producto = p_codigo AND oc.status = 'emitido'
  )
  ORDER BY fecha DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

-- 11. Migración: renombrar tabla tazas → tasas (ejecutar solo si existe la tabla vieja)
-- NOTA: ejecutar este bloque SOLO si se está migrando desde una instalación anterior.
-- En instalaciones nuevas, la tabla ya se crea como "tasas" (paso 3 arriba).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'tazas')
     AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'tasas')
  THEN
    ALTER TABLE public.tazas RENAME TO tasas;
    RAISE NOTICE 'Tabla "tazas" renombrada a "tasas" exitosamente.';
  END IF;
END $$;
