import { Conversation } from './types';

export interface RecruiterArchitectureMetric {
  title: string;
  value: string;
  badge: string;
  description: string;
  technicalDetails: string[];
}

export const DEMO_ARCHITECTURE_PILLARS: RecruiterArchitectureMetric[] = [
  {
    title: 'Pipeline RAG de 5 Capas',
    value: 'Sub-14ms AST Match',
    badge: 'Zero Hallucination',
    description: 'Búsqueda determinista escalonada sobre catálogo de 7.650 SKUs ferreteros e industriales.',
    technicalDetails: [
      'Capa 01: Determinismo AST Regex (<2ms, 0 tokens, 100% exactitud)',
      'Capa 02: Normalización & Diccionario de Sinónimos de Taller',
      'Capa 03: Fuzzy String Matching con pg_trgm (GIN Index)',
      'Capa 04: Búsqueda Semántica Vectorial con pgvector (HNSW Cosine)',
      'Capa 05: Fallback con LLM & Structured JSON Validation',
    ],
  },
  {
    title: 'Orquestación n8n & Deduplicación',
    value: '33 Nodos / Zero-Desync',
    badge: 'High Concurrency',
    description: 'Control de flujo distribuido con cola de deduplicación en memoria para mitigar reintentos de WhatsApp.',
    technicalDetails: [
      'Filtro de deduplicación en ventana temporal de 60 segundos',
      'Enrutamiento condicional según intención y estado de la sesión',
      'Integración desacoplada con pasarela WAHA y Supabase Vector DB',
      'Manejo de timeouts y circuitos de recuperación automática',
    ],
  },
  {
    title: 'Resiliencia & Catch-Up Autónomo',
    value: 'Zero Data Loss',
    badge: 'Fault Tolerant',
    description: 'Mecanismo de auto-recuperación ante cortes eléctricos o caídas de red para procesar mensajes pendientes.',
    technicalDetails: [
      'Catch-up script en PowerShell que sincroniza estado con Supabase',
      'Túneles Cloudflare dinámicos con auto-reconectador en background',
      'Preservación de orden de mensajes mediante marcas de tiempo UTC',
      'Heartbeat cada 30s con alertas de telemetría en tiempo real',
    ],
  },
  {
    title: 'Salida JSON estructurada',
    value: '80.6% Resolución Autónoma',
    badge: 'Enterprise Grade',
    description: 'Validación estricta de esquemas para cotizaciones, métodos de pago y políticas de retiro en tienda.',
    technicalDetails: [
      'Esquema JSON estricto para precios exactos sin IVA inventado',
      'Políticas de atención: Pago Móvil, Zelle, Transferencia Banesco/Mercantil',
      'Detección automática de intención de compra vs. soporte técnico',
      'Transferencia a agente humano ante consultas fuera de inventario',
    ],
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'demo-conv-1',
    name: 'Alejandro Morales (Herrero)',
    phone: '+58 414-883-9021',
    status: 'qualified',
    statusLabel: 'COTIZADO (AUTO)',
    score: 96,
    intent: 'Discos de corte 4 1/2" y Electrodos 6013',
    budget: '$38.50 USD',
    schedule: 'Retiro Hoy 2:30 PM',
    silentMode: false,
    lastTime: '10:48 AM',
    messages: [
      {
        id: 'm1-1',
        sender: 'client',
        text: 'Buenas tardes amigo, ¿a cuánto tienes la caja de discos de corte de 4 1/2 DeWalt y un kilo de electrodo 6013 1/8?',
        time: '10:46 AM',
      },
      {
        id: 'm1-2',
        sender: 'agent',
        text: '¡Buenas tardes Alejandro! Con gusto. La caja de 10 Discos de Corte DeWalt 4 1/2" está en $12.50 USD y el Kilo de Electrodos E6013 1/8" en $3.80 USD. Total: $16.30 USD. ¿Deseas apartarlos para retirar en mostrador?',
        time: '10:47 AM',
        latency: '11ms',
        cost: '$0.0000',
      },
      {
        id: 'm1-3',
        sender: 'client',
        text: 'Sí porfa, apártame 2 cajas de discos y 3 kilos de electrodo. Paso a las 2:30 PM.',
        time: '10:48 AM',
      },
    ],
  },
  {
    id: 'demo-conv-2',
    name: 'Mariana Gómez (Hogar / Pintura)',
    phone: '+58 424-712-3349',
    status: 'in-progress',
    statusLabel: 'EN CURSO',
    score: 84,
    intent: 'Pintura Caucho Blanco Mate & Rodillo',
    budget: '$22.50 USD',
    schedule: 'En Asesoría',
    silentMode: false,
    lastTime: '10:40 AM',
    messages: [
      {
        id: 'm2-1',
        sender: 'client',
        text: 'Hola, buenos días. ¿Tienen pintura de caucho para interiores color blanco marfil o mate?',
        time: '10:38 AM',
      },
      {
        id: 'm2-2',
        sender: 'agent',
        text: '¡Hola Mariana! Sí, disponemos de Pintura Caucho Clase A Blanco Mate (Galón Manpica) en $16.00 USD. También tenemos kit de rodillo antigoteo con bandeja en $4.50 USD. ¿Te gustaría incluir el rodillo?',
        time: '10:39 AM',
        latency: '14ms',
        cost: '$0.0000',
      },
      {
        id: 'm2-3',
        sender: 'client',
        text: 'Sí, el galón y el rodillo. ¿Tienen Pago Móvil a tasa oficial?',
        time: '10:40 AM',
      },
    ],
  },
  {
    id: 'demo-conv-3',
    name: 'José Gregorio Peña (Electricista)',
    phone: '+58 412-409-1188',
    status: 'qualified',
    statusLabel: 'COTIZADO (AUTO)',
    score: 92,
    intent: 'Cable 12 AWG THHN y Breakers',
    budget: '$64.00 USD',
    schedule: 'Retiro en Sede',
    silentMode: false,
    lastTime: '10:32 AM',
    messages: [
      {
        id: 'm3-1',
        sender: 'client',
        text: 'Hermano, ¿precio del rollo de 100m de cable 12 AWG THHN marca Cabel y un breaker doble de 30 amp?',
        time: '10:30 AM',
      },
      {
        id: 'm3-2',
        sender: 'agent',
        text: '¡Saludos José! El Rollo Cable 12 AWG THHN 100m está en $54.00 USD y el Breaker Enchufable 2 Polos 30A (Bticino) en $10.00 USD. Total: $64.00 USD. Disponibles para entrega inmediata.',
        time: '10:31 AM',
        latency: '16ms',
        cost: '$0.0000',
      },
      {
        id: 'm3-3',
        sender: 'client',
        text: 'Excelente, guárdamelos que voy saliendo a la tienda.',
        time: '10:32 AM',
      },
    ],
  },
  {
    id: 'demo-conv-4',
    name: 'Dra. Valeria Rincón',
    phone: '+58 416-302-8819',
    status: 'closed',
    statusLabel: 'FINALIZADO',
    score: 75,
    intent: 'Horario y Sede Principal',
    budget: '$0.00 USD',
    schedule: 'Atendido',
    silentMode: false,
    lastTime: '09:50 AM',
    messages: [
      {
        id: 'm4-1',
        sender: 'client',
        text: '¿Cuál es el horario de atención para retirar en la sede principal?',
        time: '09:48 AM',
      },
      {
        id: 'm4-2',
        sender: 'agent',
        text: 'Nuestro horario de atención en sede principal es de Lunes a Viernes de 8:00 AM a 5:00 PM (horario corrido) y Sábados de 8:30 AM a 2:00 PM. ¡Te esperamos Valeria!',
        time: '09:50 AM',
        latency: '9ms',
        cost: '$0.0000',
      },
    ],
  },
  {
    id: 'demo-conv-5',
    name: 'Sr. Roberto Díaz (Plomería)',
    phone: '+58 424-651-7700',
    status: 'in-progress',
    statusLabel: 'EN CURSO',
    score: 87,
    intent: 'Tubería PVC 1/2" y Pegamento Tangit',
    budget: '$28.00 USD',
    schedule: 'En Proceso',
    silentMode: false,
    lastTime: '09:35 AM',
    messages: [
      {
        id: 'm5-1',
        sender: 'client',
        text: 'Buen día, ¿tienen tubos de PVC para agua blanca de 1/2 pulgada de 6 metros y pegamento para PVC?',
        time: '09:33 AM',
      },
      {
        id: 'm5-2',
        sender: 'agent',
        text: '¡Buen día Roberto! Sí, el Tubo PVC Presión 1/2" x 6m (Tubrica) está en $4.20 USD la barra y el Pegamento PVC SoldaMax 1/4 galón en $7.50 USD. ¿Cuántos tubos requieres?',
        time: '09:34 AM',
        latency: '12ms',
        cost: '$0.0000',
      },
      {
        id: 'm5-3',
        sender: 'client',
        text: 'Necesito 4 tubos y un pote de pegamento.',
        time: '09:35 AM',
      },
    ],
  },
  {
    id: 'demo-conv-6',
    name: 'Patricia Velásquez (Hogar / Seguridad)',
    phone: '+58 414-331-5509',
    status: 'qualified',
    statusLabel: 'COTIZADO (AUTO)',
    score: 90,
    intent: 'Cerradura Sobreponer Cisa & Candado',
    budget: '$45.00 USD',
    schedule: 'Retiro Sábado',
    silentMode: false,
    lastTime: '09:12 AM',
    messages: [
      {
        id: 'm6-1',
        sender: 'client',
        text: 'Hola, ¿tienen cerradura Cisa de pomo o sobreponer para puerta principal?',
        time: '09:10 AM',
      },
      {
        id: 'm6-2',
        sender: 'agent',
        text: '¡Hola Patricia! Disponemos de Cerradura de Sobreponer Cisa Original (Llave de Cruz) en $32.00 USD y Candado Cisa 50mm en $13.00 USD. Ambos con garantía de fábrica.',
        time: '09:11 AM',
        latency: '13ms',
        cost: '$0.0000',
      },
      {
        id: 'm6-3',
        sender: 'client',
        text: 'Perfecto, paso el sábado en la mañana a buscar la cerradura.',
        time: '09:12 AM',
      },
    ],
  },
  {
    id: 'demo-conv-7',
    name: 'Constructora Horizonte C.A.',
    phone: '+58 414-982-1144',
    status: 'qualified',
    statusLabel: 'MAYORISTA B2B',
    score: 98,
    intent: 'Cotización Cemento Portland 50 sacos',
    budget: '$425.00 USD',
    schedule: 'Despacho Programado',
    silentMode: false,
    lastTime: '08:40 AM',
    messages: [
      {
        id: 'm7-1',
        sender: 'client',
        text: 'Buenos días, requerimos 50 sacos de Cemento Gris Portland Tipo I con factura fiscal.',
        time: '08:38 AM',
      },
      {
        id: 'm7-2',
        sender: 'agent',
        text: '¡Buenos días! Disponemos de Cemento Gris Portland Tipo I (Saco 42.5kg) a $8.50 por unidad. Total: $425.00 USD. Emitimos factura fiscal y aceptamos transferencias Banesco, Mercantil y Zelle corporativo.',
        time: '08:39 AM',
        latency: '11ms',
        cost: '$0.0000',
      },
      {
        id: 'm7-3',
        sender: 'client',
        text: 'Perfecto, envíame los datos bancarios para emitir la orden de pago.',
        time: '08:40 AM',
      },
    ],
  },
];
