import { Conversation } from './types';

export interface RecruiterArchitectureMetric {
  title: string;
  value: string;
  badge: string;
  description: string;
  technicalDetails: string[];
}

export const DEMO_ARCHITECTURE_PILLARS: RecruiterArchitectureMetric[] = [
  {
    title: 'Pipeline RAG de 5 Capas',
    value: 'Sub-14ms AST Match',
    badge: 'Zero Hallucination',
    description: 'Búsqueda determinista escalonada sobre catálogo de 7.650 SKUs ferreteros e industriales.',
    technicalDetails: [
      'Capa 01: Determinismo AST Regex (<2ms, 0 tokens, 100% exactitud)',
      'Capa 02: Normalización & Diccionario de Sinónimos de Taller',
      'Capa 03: Fuzzy String Matching con pg_trgm (GIN Index)',
      'Capa 04: Búsqueda Semántica Vectorial con pgvector (HNSW Cosine)',
      'Capa 05: Fallback con LLM & Structured JSON Validation',
    ],
  },
  {
    title: 'Orquestación n8n & Deduplicación',
    value: '33 Nodos / Zero-Desync',
    badge: 'High Concurrency',
    description: 'Control de flujo distribuido con cola de deduplicación en memoria para mitigar reintentos de WhatsApp.',
    technicalDetails: [
      'Filtro de deduplicación en ventana temporal de 60 segundos',
      'Enrutamiento condicional según intención y estado de la sesión',
      'Integración desacoplada con pasarela WAHA y Supabase Vector DB',
      'Manejo de timeouts y circuitos de recuperación automática',
    ],
  },
  {
    title: 'Resiliencia & Catch-Up Autónomo',
    value: 'Zero Data Loss',
    badge: 'Fault Tolerant',
    description: 'Mecanismo de auto-recuperación ante cortes eléctricos o caídas de red para procesar mensajes pendientes.',
    technicalDetails: [
      'Catch-up script en PowerShell que sincroniza estado con Supabase',
      'Túneles Cloudflare dinámicos con auto-reconectador en background',
      'Preservación de orden de mensajes mediante marcas de tiempo UTC',
      'Heartbeat cada 30s con alertas de telemetría en tiempo real',
    ],
  },
  {
    title: 'Salida JSON estructurada',
    value: '80.6% Resolución Autónoma',
    badge: 'Enterprise Grade',
    description: 'Validación estricta de esquemas para cotizaciones, métodos de pago y políticas de retiro en tienda.',
    technicalDetails: [
      'Esquema JSON estricto para precios exactos sin IVA inventado',
      'Políticas de atención: Pago Móvil, Zelle, Transferencia Banesco/Mercantil',
      'Detección automática de intención de compra vs. soporte técnico',
      'Transferencia a agente humano ante consultas fuera de inventario',
    ],
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'demo-conv-suly',
    name: 'Suly',
    phone: '+58 414-235-4263',
    status: 'qualified',
    statusLabel: 'RESERVA CONFIRMADA',
    score: 96,
    intent: '10 Láminas 12ft, Ganchos, Tubos 2x1 y Cemento',
    budget: '$340.00 USD',
    schedule: 'Retiro en Mostrador (Mene Mauroa)',
    silentMode: false,
    lastTime: '09:34 AM',
    messages: [
      {
        id: 'm1-1',
        sender: 'client',
        text: '🛒 RESERVA: 10 Láminas de 12, 1 Caja de ganchos, 5 Tubos de 2x1, 2 Tubos de 1.5x3, 1 Saco de Cemento, 1 Cercha',
        time: '09:34 AM',
      },
      {
        id: 'm1-2',
        sender: 'agent',
        text: '¡Hola Suly! 👨🏻‍💼 Tu reserva fue registrada con éxito en el inventario. Materiales listos y apartados para retiro en tienda física. Aceptamos transferencias y divisas en caja.',
        time: '09:34 AM',
        latency: '19ms',
        cost: '$0.0000',
      },
    ],
  },
  {
    id: 'demo-conv-yanerys',
    name: 'Yanerys Sánchez Navarro',
    phone: '+58 416-263-1544',
    status: 'qualified',
    statusLabel: 'RESERVA CONFIRMADA',
    score: 94,
    intent: 'Protector de Voltaje Vitron Refrigeración',
    budget: '$28.00 USD',
    schedule: 'Retiro en Tienda (Hoy)',
    silentMode: false,
    lastTime: '11:20 AM',
    messages: [
      {
        id: 'm2-1',
        sender: 'client',
        text: '🛒 RESERVA: Protector DE Voltaje P/refrig Y Neveras Vitron 110V',
        time: '11:18 AM',
      },
      {
        id: 'm2-2',
        sender: 'agent',
        text: '¡Hola Yanerys! 👨🏻‍🔧 Confirmado en inventario: Protector de Voltaje Vitron 110V con retardo de reconexión a $28.00 USD. Tu reserva está registrada y lista para entrega en mostrador.',
        time: '11:20 AM',
        latency: '19ms',
        cost: '$0.0000',
      },
    ],
  },
  {
    id: 'demo-conv-matilde',
    name: 'Matilde Páez (Pastor Cruz)',
    phone: '+58 424-443-0700',
    status: 'in-progress',
    statusLabel: 'EN MOSTRADOR',
    score: 88,
    intent: 'Cadena Metálica Galvanizada por Metro',
    budget: '$45.00 USD',
    schedule: 'Retiro en Tienda',
    silentMode: false,
    lastTime: '10:05 AM',
    messages: [
      {
        id: 'm3-1',
        sender: 'client',
        text: 'Buenos días, tienen cadena metálica fina de eslabón corto por metro?',
        time: '10:02 AM',
      },
      {
        id: 'm3-2',
        sender: 'agent',
        text: '¡Buenos días Matilde! 👨🏻‍🔧 Sí, disponemos de Cadena Galvanizada 3/16" y 1/4" a $2.20 el metro. ¿Cuántos metros requieres cortar para tu trabajo?',
        time: '10:05 AM',
        latency: '14ms',
        cost: '$0.0000',
      },
    ],
  },
  {
    id: 'demo-conv-diego',
    name: 'Diego Bracho',
    phone: '+58 412-110-2992',
    status: 'in-progress',
    statusLabel: 'COTIZACIÓN ELÉCTRICA',
    score: 92,
    intent: 'Cables AWG, Tubos PVC 3/4 y Codos',
    budget: '$215.00 USD',
    schedule: 'Despacho Programado',
    silentMode: false,
    lastTime: '12:15 PM',
    messages: [
      {
        id: 'm4-1',
        sender: 'client',
        text: 'Buenos días, presupuesto para: Cable AWG #14 (3 rollos), Cable AWG #12 (4 rollos), Tubo PVC Eléctrico 3/4 (28 tubos) y 24 curvas 3/4.',
        time: '12:10 PM',
      },
      {
        id: 'm4-2',
        sender: 'agent',
        text: '¡Saludos Diego! 👨🏻‍🔧 Lista verificada en catálogo de 7.650 SKUs. Disponemos de cable THW 100% cobre y tubería PVC rígida con curvas de fábrica. Presupuesto total procesado.',
        time: '12:15 PM',
        latency: '28ms',
        cost: '$0.0000',
      },
    ],
  },
  {
    id: 'demo-conv-carlos',
    name: 'Carlos Mendoza',
    phone: '+58 424-647-8892',
    status: 'closed',
    statusLabel: 'VENTA CERRADA',
    score: 95,
    intent: '40 Sacos Cemento Gris & 200 Bloques',
    budget: '$530.00 USD',
    schedule: 'Retiro en Sucursal (Hoy 2:00 PM)',
    silentMode: false,
    lastTime: '01:02 PM',
    messages: [
      {
        id: 'm5-1',
        sender: 'client',
        text: 'Buenas tardes, necesito cotizar 40 sacos de cemento gris y 200 bloques para retirar hoy.',
        time: '01:00 PM',
      },
      {
        id: 'm5-2',
        sender: 'agent',
        text: '¡Buenas tardes Carlos! 👨🏻‍🔧 Cemento Gris Tipo I en $8.50 el saco ($340.00) y Bloque de Concreto 15cm en $0.95 ($190.00). Total $530.00 USD. ¿Retiras en sucursal o necesitas transporte?',
        time: '01:00 PM',
        latency: '18ms',
        cost: '$0.0000',
      },
      {
        id: 'm5-3',
        sender: 'client',
        text: 'Excelente precio. Para retirar en sucursal hoy a las 2:00 PM.',
        time: '01:02 PM',
      },
      {
        id: 'm5-4',
        sender: 'agent',
        text: 'Perfecto Carlos. Te reservé la orden con presupuesto de $530.00 USD para las 2:00 PM. El personal de patio tendrá todo listo en mostrador.',
        time: '01:02 PM',
        latency: '~700ms',
        cost: '$0.00012',
      },
    ],
  },
  {
    id: 'demo-conv-rafer',
    name: 'Rafer Jesús',
    phone: '+58 414-562-6474',
    status: 'escalated',
    statusLabel: 'ATENCIÓN ESPECIAL',
    score: 89,
    intent: 'Bloques de 10 con Flete a Campo Piñita',
    budget: '$180.00 USD',
    schedule: 'Despacho Camión a Campo Piñita',
    silentMode: true,
    lastTime: '02:54 PM',
    messages: [
      {
        id: 'm6-1',
        sender: 'client',
        text: 'Buenas, cuánto sale el ciento de bloque de diez normal y el transporte incluido para Campo Piñita, para pagar por pago móvil de una vez?',
        time: '02:50 PM',
      },
      {
        id: 'm6-2',
        sender: 'agent',
        text: '¡Hola Rafer! 👨🏻‍🔧 El bloque de 10 normal está en $0.95 c/u ($95 por ciento). He transferido la cotización del flete a Campo Piñita a nuestro coordinador de despacho para coordinar la carga de inmediato.',
        time: '02:54 PM',
        latency: '32ms',
        cost: '$0.0000',
      },
    ],
  },
  {
    id: 'demo-conv-linda',
    name: 'Linda Ferrer',
    phone: '+58 416-105-8367',
    status: 'in-progress',
    statusLabel: 'EN ASESORÍA',
    score: 86,
    intent: 'Cuñete de Pintura Blanca Interior',
    budget: '$55.00 USD',
    schedule: 'Retiro en Tienda',
    silentMode: false,
    lastTime: '05:56 PM',
    messages: [
      {
        id: 'm7-1',
        sender: 'client',
        text: 'Hola tiene pintura blanca de cuñete',
        time: '05:54 PM',
      },
      {
        id: 'm7-2',
        sender: 'agent',
        text: '¡Hola Linda! 👨🏻‍🔧 Sí, disponemos de Cuñete de Pintura Caucho Blanca clase B a $38.00 USD y clase A lavable a $55.00 USD para entrega inmediata en tienda.',
        time: '05:56 PM',
        latency: '15ms',
        cost: '$0.0000',
      },
    ],
  },
];
